homeassistant:
  # Name of the location where Home Assistant is running
  name: La Chiquita
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 63
# metric for Metric, imperial for Imperial
  unit_system: imperial
   # C for Celcius, F for Fahrenheit
  temperature_unit: F
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# ISY994
isy994:
  host: !secret isy994_hostname
  username: !secret isy994_username
  password: !secret isy994_password

# Garage doors
cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: liftmaster

# Nest Thermometer
nest:
  client_id: !secret nest_clientid 
  client_secret: !secret nest_secret

# Ecobee Thermometer
ecobee:
  api_key: !secret ecobee_api_key 

# Support for Arlo Netgear cameras. First add generic component then camera config.
#arlo:
#  username: !secret arlo_username
#  password: !secret arlo_password

#alarm_control_panel:
#  - platform: arlo
#    home_mode_name: "Disarmed"
#    away_mode_name: "Armed"

#sensor:
#  - platform: arlo
#    monitored_conditions:
#      - captured_today
#      - last_capture
#      - total_cameras
#      - battery_level
#      - signal_strength

# Arlo requires ffmpeg
#ffmpeg:

#camera:
#  - platform: arlo
#    ffmpeg_arguments: '-pred 1 -q:v 2'
  
# This utilizes the homeassistant cloud (https://www.nabucasa.com)
# Currently we are utilizing this for Alexa integration. You can
# also integrate with Amazon Alexa directly giving much more flexibility
# That integration is documented here: https://www.home-assistant.io/components/alexa/
cloud:
  alexa:
    filter:
      include_entities:
        - switch.boyslights
        - switch.dinner_scene
        - switch.frontdoor_motion
        - switch.manual_sprinklers
        - switch.1stlivingroomdraperelay
        - switch.b__fmly_btn_upstairs_off
        - media_player.xbr75x850c
#      include_domains:
#        - switch
      exclude_domains:
        - light
    entity_config:
      switch.boyslights:
        name: boys lights
        description: All the boys lights
        display_categories: LIGHT
      switch.1stlivingroomdraperelay:
        name: drapes
        description: Open/Close Drapes in Living room
        display_categories: SWITCH
      switch.dinner_scene:
        name: dinner scene
        description: Lighting for dinner time
        display_categories: SCENE_TRIGGER
      switch.frontdoor_motion:
        name: frontdoor motion
        description: Control turning on/off front door voice notification
        display_categories: SWITCH
      switch.manual_sprinklers:
        name: sprinklers
        description: Control turning on/off 3 sprinkler zones (manual run)
        display_categories: SWITCH
      switch.b__fmly_btn_upstairs_off:
        name: upstairs 
        description: Upstairs lights
        display_categories: LIGHT

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
