# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

logger:
  default: info
  logs:
    custom_components.aarlo: debug
    custom_components.aarlo.camera: debug
    pyaarlo: debug

frontend:
  themes: !include themes.yaml

# ISY994
isy994:
  host: !secret isy994_hostname
  username: !secret isy994_username
  password: !secret isy994_password

# Garage doors
cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: liftmaster

# Ecobee Thermometer
ecobee:
  api_key: !secret ecobee_api_key 

# Arlo Cameras
aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  refresh_devices_every: 2
  stream_timeout: 60
  reconnect_every: 90

camera:
  - platform: aarlo

tts:
  - platform: voicerss
    api_key: !secret voicerss_api_key
    format: 44khz_16bit_stereo

# This utilizes the homeassistant cloud (https://www.nabucasa.com)
# Currently we are utilizing this for Alexa integration. You can
# also integrate with Amazon Alexa directly giving much more flexibility
# That integration is documented here: https://www.home-assistant.io/components/alexa/
cloud:
  alexa:
    filter:
      include_entities:
        - switch.boyslights
        - switch.dinner_scene
        - switch.frontdoor_motion
        - switch.manual_sprinklers
        - switch.1stlivingroomdraperelay
        - switch.b_fmly_btn_upstairs_off
        - switch.fmly_master_btn
        - switch.nook_master_btn
        - switch.kitchen_master_btn
        - media_player.xbr75x850c
      include_domains:
        - switch
#      exclude_domains:
#        - light
    entity_config:
      switch.boyslights:
        name: boys lights
        description: All the boys lights
        display_categories: LIGHT
      switch.1stlivingroomdraperelay:
        name: drapes
        description: Open/Close Drapes in Living room
        display_categories: SWITCH
      switch.dinner_scene:
        name: dinner scene
        description: Lighting for dinner time
        display_categories: SCENE_TRIGGER
      switch.frontdoor_motion:
        name: frontdoor motion
        description: Control turning on/off front door voice notification
        display_categories: SWITCH
      switch.manual_sprinklers:
        name: sprinklers
        description: Control turning on/off 3 sprinkler zones (manual run)
        display_categories: SWITCH
      switch.b_fmly_btn_upstairs_off:
        name: upstairs 
        description: Upstairs lights
        display_categories: LIGHT
      switch.fmly_master_btn:
        name: family room
        description: Family room lights
        display_categories: SWITCH
      switch.nook_master_btn:
        name: nook
        description: Nook lights
        display_categories: SWITCH
      switch.kitchen_master_btn:
        name: kitchen
        description: Kitchen lights
        display_categories: SWITCH
      switch.office_lights:
        name: office
        description: Office lights
        display_categories: SWITCH

# All the below is for the sprinkler integration
input_datetime:
  zone_garden_am_on_time:
    name: AM On Time
    has_date: false
    has_time: true

  zone_garden_pm_on_time:
    name: PM On Time
    has_date: false
    has_time: true

  zone_frontyard_am_on_time:
    name: AM On Time
    has_date: false
    has_time: true

  zone_frontyard_pm_on_time:
    name: PM On Time
    has_date: false
    has_time: true

  zone_backyard_am_on_time:
    name: AM On Time
    has_date: false
    has_time: true

  zone_backyard_pm_on_time:
    name: PM On Time
    has_date: false
    has_time: true

input_boolean:
  zone_garden_mon:
    name: Monday
    icon: mdi:calendar

  zone_garden_tue:
    name: Tuesday
    icon: mdi:calendar

  zone_garden_wed:
    name: Wednesday
    icon: mdi:calendar

  zone_garden_thu:
    name: Thursday
    icon: mdi:calendar

  zone_garden_fri:
    name: Friday
    icon: mdi:calendar

  zone_garden_sat:
    name: Saturday
    icon: mdi:calendar

  zone_garden_sun:
    name: Sunday
    icon: mdi:calendar

  zone_frontyard_mon:
    name: Monday
    icon: mdi:calendar

  zone_frontyard_tue:
    name: Tuesday
    icon: mdi:calendar

  zone_frontyard_wed:
    name: Wednesday
    icon: mdi:calendar

  zone_frontyard_thu:
    name: Thursday
    icon: mdi:calendar

  zone_frontyard_fri:
    name: Friday
    icon: mdi:calendar

  zone_frontyard_sat:
    name: Saturday
    icon: mdi:calendar

  zone_frontyard_sun:
    name: Sunday
    icon: mdi:calendar

  zone_backyard_mon:
    name: Monday
    icon: mdi:calendar

  zone_backyard_tue:
    name: Tuesday
    icon: mdi:calendar

  zone_backyard_wed:
    name: Wednesday
    icon: mdi:calendar

  zone_backyard_thu:
    name: Thursday
    icon: mdi:calendar

  zone_backyard_fri:
    name: Friday
    icon: mdi:calendar

  zone_backyard_sat:
    name: Saturday
    icon: mdi:calendar

  zone_backyard_sun:
    name: Sunday
    icon: mdi:calendar

  manual_sprinkler_switch:
    initial: false
    name: Manual Sprinkler Switch
    icon: mdi:sprout

input_number:
  zone_garden_run_time:
    name: Run Time
    min: 5
    max: 40
    step: 5
    unit_of_measurement: min
    icon: mdi:clock
  zone_frontyard_run_time:
    name: Run Time
    min: 5
    max: 40
    step: 5
    unit_of_measurement: min
    icon: mdi:clock
  zone_backyard_run_time:
    name: Run Time
    min: 5
    max: 40
    step: 5
    unit_of_measurement: min
    icon: mdi:clock
  manual_sprinkler_run_time:
    name: Run Time
    min: 5
    max: 15
    step: 1
    unit_of_measurement: min
    icon: mdi:clock

binary_sensor:
  - platform: template
    sensors:
      zone_backyard_day_active:
        friendly_name: Irrigation Day Active
        entity_id:
          - sensor.date
          - input_boolean.zone_backyard_mon
          - input_boolean.zone_backyard_tue
          - input_boolean.zone_backyard_wed
          - input_boolean.zone_backyard_thu
          - input_boolean.zone_backyard_fri
          - input_boolean.zone_backyard_sat
          - input_boolean.zone_backyard_sun
        value_template: >-
          {{ ( is_state('input_boolean.zone_backyard_mon', 'on') and now().weekday() == 0 )
          or ( is_state('input_boolean.zone_backyard_tue', 'on') and now().weekday() == 1 )
          or ( is_state('input_boolean.zone_backyard_wed', 'on') and now().weekday() == 2 )
          or ( is_state('input_boolean.zone_backyard_thu', 'on') and now().weekday() == 3 )
          or ( is_state('input_boolean.zone_backyard_fri', 'on') and now().weekday() == 4 )
          or ( is_state('input_boolean.zone_backyard_sat', 'on') and now().weekday() == 5 )
          or ( is_state('input_boolean.zone_backyard_sun', 'on') and now().weekday() == 6 ) }}    
      zone_frontyard_day_active:
        friendly_name: Irrigation Day Active
        entity_id:
          - sensor.date
          - input_boolean.zone_frontyard_mon
          - input_boolean.zone_frontyard_tue
          - input_boolean.zone_frontyard_wed
          - input_boolean.zone_frontyard_thu
          - input_boolean.zone_frontyard_fri
          - input_boolean.zone_frontyard_sat
          - input_boolean.zone_frontyard_sun
        value_template: >-
          {{ ( is_state('input_boolean.zone_frontyard_mon', 'on') and now().weekday() == 0 )
          or ( is_state('input_boolean.zone_frontyard_tue', 'on') and now().weekday() == 1 )
          or ( is_state('input_boolean.zone_frontyard_wed', 'on') and now().weekday() == 2 )
          or ( is_state('input_boolean.zone_frontyard_thu', 'on') and now().weekday() == 3 )
          or ( is_state('input_boolean.zone_frontyard_fri', 'on') and now().weekday() == 4 )
          or ( is_state('input_boolean.zone_frontyard_sat', 'on') and now().weekday() == 5 )
          or ( is_state('input_boolean.zone_frontyard_sun', 'on') and now().weekday() == 6 ) }}
      zone_garden_day_active:
        friendly_name: Irrigation Day Active
        entity_id:
          - sensor.date
          - input_boolean.zone_garden_mon
          - input_boolean.zone_garden_tue
          - input_boolean.zone_garden_wed
          - input_boolean.zone_garden_thu
          - input_boolean.zone_garden_fri
          - input_boolean.zone_garden_sat
          - input_boolean.zone_garden_sun
        value_template: >-
          {{ ( is_state('input_boolean.zone_garden_mon', 'on') and now().weekday() == 0 )
          or ( is_state('input_boolean.zone_garden_tue', 'on') and now().weekday() == 1 )
          or ( is_state('input_boolean.zone_garden_wed', 'on') and now().weekday() == 2 )
          or ( is_state('input_boolean.zone_garden_thu', 'on') and now().weekday() == 3 )
          or ( is_state('input_boolean.zone_garden_fri', 'on') and now().weekday() == 4 )
          or ( is_state('input_boolean.zone_garden_sat', 'on') and now().weekday() == 5 )
          or ( is_state('input_boolean.zone_garden_sun', 'on') and now().weekday() == 6 ) }}    

sensor:
# ISY994 PGE Energy tracker
  - platform: command_line
    name: Home Solar Production
    command: "cat /config/solar.txt"
    unit_of_measurement: "kW"

# Sunpower solar energy tracker
  - platform: command_line
    name: Home Power Usage
    command: "python3 /config/emeter.py"
    unit_of_measurement: "kW"

  - platform: template
    sensors:
      solar_power:
        friendly_name: 'Solar Power Production'
        unit_of_measurement: 'W'
        value_template: >-
          {{ (states("sensor.home_solar_production") | float) | int }}
      grid_power_consumption:
        friendly_name: 'Grid power consumption'
        unit_of_measurement: 'W'
        value_template: >-
          {{ (states("sensor.home_power_usage") | float) | int }}

  - platform: time_date
    display_options:
      - 'time'
      - 'date'
    
  - platform: template
    sensors:
      zone_garden_time_remaining:
        friendly_name: 'Time Remaining'
        entity_id:
          - input_number.zone_garden_time_remaining
          - sensor.time
          - switch.garden_sprinklers
        value_template: "{{ [ (states('input_number.zone_garden_run_time') | int - (as_timestamp(now()) - as_timestamp(states.switch.garden_sprinklers.last_changed)) / 60) | round(0) ,0 ] | max }}"
      zone_frontyard_time_remaining:
        friendly_name: 'Time Remaining'
        entity_id:
          - input_number.zone_frontyard_time_remaining
          - sensor.time
          - switch.frontyard_sprinklers
        value_template: "{{ [ (states('input_number.zone_frontyard_run_time') | int - (as_timestamp(now()) - as_timestamp(states.switch.frontyard_sprinklers.last_changed)) / 60) | round(0) ,0 ] | max }}"
      zone_backyard_time_remaining:
        friendly_name: 'Time Remaining'
        entity_id:
          - input_number.zone_backyard_time_remaining
          - sensor.time
          - switch.backyard_sprinklers
        value_template: "{{ [ (states('input_number.zone_backyard_run_time') | int - (as_timestamp(now()) - as_timestamp(states.switch.backyard_sprinklers.last_changed)) / 60) | round(0) ,0 ] | max }}"

switch:
  - platform: command_line
    switches:
      somfy_drapes:
        command_on: "python3 /config/drape_open.py 2> /config/command.log"
        command_off: "python3 /config/drape_close.py 2> /config/command.log"
        friendly_name: Living Room Drapes

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
